!!brut.androlib.meta.MetaInfo
apkFileName: VoIProxy.apk
compressionType: false
doNotCompress:
- png
isFrameworkApk: false
packageInfo:
  forcedPackageId: '127'
  renameManifestPackage: null
sdkInfo:
  minSdkVersion: '15'
  targetSdkVersion: '25'
sharedLibrary: false
sparseResources: false
unknownFiles: {}
usesFramework:
  ids:
  - 1
  tag: null
version: 2.5.0
versionInfo:
  versionCode: '1'
  versionName: '1.0'
